"""
Case studies — a mix of named client precedents (from predictive-labs.yaml) and
anonymized "current engagements" derived from the live public-sector bid
pipeline. We never name a public body we haven't won work with yet.
"""

BID_DERIVED = [
    {
        "id": "nordic-health-rwd",
        "title": "Real-world data for precision cancer medicine",
        "buyer": "Major Nordic national medicines authority",
        "country": "Denmark",
        "flag": "🇩🇰",
        "sector": "Health",
        "status": "Active engagement",
        "problem": "Ongoing validation of new cancer medicines in real-world patient populations, against fragmented national health registries.",
        "approach": "Privacy-preserving pipeline over LPR3-class inpatient data, pharmacy dispensing, and civil-registry linkage, with reusable protocol templates that compress follow-up cycles from nine months to three.",
        "capability": "Regulatory-grade epidemiology, Git-versioned analytical code, sworn translation, monthly steering cadence.",
        "tech": ["Python", "DuckDB", "PostGIS", "dbt", "Quarto", "GDPR-native pipelines"],
    },
    {
        "id": "uk-traffic-od",
        "title": "County-wide traffic and origin-destination analytics",
        "buyer": "UK county council",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "sector": "Public management · Mobility",
        "status": "Active engagement",
        "problem": "Fourteen local authorities, fragmented ANPR/Bluetooth feeds, and an annual commercial GPS licence the council wanted to replace.",
        "approach": "Doubly-constrained gravity models fused with UK Census and DfT open data, served through an interactive dashboard and REST API. Methodology published on GitHub as open-od-toolkit.",
        "capability": "Open-source replacement for commercial mobility data; no vendor lock-in.",
        "tech": ["Python", "GeoPandas", "FastAPI", "H3", "open-od-toolkit"],
    },
    {
        "id": "nordic-city-signal",
        "title": "Real-time traffic situation picture with anomaly alerting",
        "buyer": "Major Nordic capital city",
        "country": "Finland",
        "flag": "🇫🇮",
        "sector": "Public management · Mobility",
        "status": "Active engagement",
        "problem": "City operators needed a unified situation picture for floating-car data with speed-anomaly detection and historical trend context.",
        "approach": "Streaming ingestion of anonymised probe data, statistical change-point detection on corridor speeds, and LLM-assisted incident summaries delivered into the operator console.",
        "capability": "From raw signals to operational insight — within one fused control surface.",
        "tech": ["LangGraph", "DuckDB", "Plotly", "WebSockets"],
    },
    {
        "id": "nordic-health-panel",
        "title": "AI and data-engineering panel for a national hospital system",
        "buyer": "Largest Nordic hospital district",
        "country": "Finland",
        "flag": "🇫🇮",
        "sector": "Health",
        "status": "Active engagement",
        "problem": "Multi-site demand for AI application development and lakehouse operations across five regional health authorities, with EU AI Act and clinical-data constraints.",
        "approach": "Joined the supplier panel across two specialisms — AI application development (LLMs, agentic workflows) and data production (Data Vault 2.0 on Databricks) — with healthcare-regulated delivery practice.",
        "capability": "EU AI Act readiness, clinical-data discipline, dual-track delivery.",
        "tech": ["Databricks", "Data Vault 2.0", "LangGraph", "Delta Lake"],
    },
    {
        "id": "nl-justice-dataplatform",
        "title": "Criminal-justice data platform for a three-agency consortium",
        "buyer": "National probation service, partnered delivery",
        "country": "Netherlands",
        "flag": "🇳🇱",
        "sector": "Public management · Justice",
        "status": "Active engagement",
        "problem": "Consolidate probation-process data for three justice organisations into one analytics platform supporting 200+ dashboards and 200+ custom analyses per year.",
        "approach": "Partnered delivery with an NL-based prime covering Dutch language and justice-sector clearance; we own the data-engineering, AI-insight, and dashboarding layers.",
        "capability": "Delivery in the most sensitive public-sector domains, under clear data-protection control.",
        "tech": ["Python", "PostgreSQL", "dbt", "Power BI", "Airflow"],
    },
    {
        "id": "dk-data-quality",
        "title": "Municipal data-quality framework",
        "buyer": "Major Danish municipality",
        "country": "Denmark",
        "flag": "🇩🇰",
        "sector": "Public management",
        "status": "Active engagement",
        "problem": "A continuous framework for ad-hoc data engineering, profiling, and quality-assurance work across municipal data estates.",
        "approach": "Registered once on the dynamic purchasing framework; individual call-offs delivered via our open-source data-quality-toolkit with declarative rules and AI-assisted anomaly detection.",
        "capability": "Inspectable, auditable alternative to closed enterprise DQM suites.",
        "tech": ["data-quality-toolkit", "Python", "Great Expectations", "DuckDB"],
    },
]


NAMED_PRECEDENTS = [
    {
        "id": "dbrs-rmbs",
        "title": "EU RMBS rating models on 2B+ records",
        "buyer": "DBRS Morningstar",
        "country": "Pan-European",
        "flag": "🇪🇺",
        "sector": "Financial services",
        "status": "Delivered",
        "problem": "Rating models for European residential mortgage-backed securities, integrating over two billion records of unstructured loan-level data.",
        "approach": "Document ingestion and extraction pipelines feeding XGBoost-based rating models, deployed via MLflow with full regulatory auditability.",
        "capability": "Document processing at scale, regulatory audit trail, production ML ops.",
        "tech": ["XGBoost", "MLflow", "Spark", "Python"],
    },
    {
        "id": "microsoft-isd",
        "title": "Enterprise GenAI and RAG for Industry Solutions Delivery",
        "buyer": "Microsoft Corporation",
        "country": "Europe",
        "flag": "🇪🇺",
        "sector": "Cross-sector",
        "status": "Delivered",
        "problem": "European enterprise clients across energy, biotech, and financial services needed production-grade retrieval-augmented generation over unstructured PDFs and platform data.",
        "approach": "Document ingestion pipelines, intelligent extraction, and enterprise platform integration under Microsoft's ISD delivery umbrella.",
        "capability": "RAG in regulated enterprise settings, multi-sector delivery.",
        "tech": ["Azure OpenAI", "LangChain", "Azure AI Search", "Python"],
    },
    {
        "id": "arm-forecasting",
        "title": "Revenue forecasting with alternative datasets",
        "buyer": "ARM Holdings plc",
        "country": "United Kingdom",
        "flag": "🇬🇧",
        "sector": "Financial services",
        "status": "Delivered",
        "problem": "Strategic foresight on royalty and non-royalty revenue trends requiring integration of external and alternative datasets.",
        "approach": "State-of-the-art time series models fused with alternative-data features; production data pipelines and enterprise-scale backtesting.",
        "capability": "Production data pipelines, alternative-data integration, enterprise scale.",
        "tech": ["Prophet", "PyTorch", "Snowflake", "Airflow"],
    },
]


ALL = BID_DERIVED + NAMED_PRECEDENTS
